language: node_js
node_js:
- '6.1.0'
cache:
  yarn: true
  directories:
    -- node_modules
script:
- yarn test -- --runInBand
after_success:
- yarn run coverage -- --runInBand
- yarn run coveralls
- yarn run codacy
before_install:
- export TZ=America/New_York
